This file will contain my first attempt at multiclass classification problem for cartoon faces
Here we import the necessary packages

In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import pandas as pd
import cv2
import os
import time
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn import metrics
from skimage.color import rgb2gray
from skimage.feature import hog
from skimage import data, exposure

Here we load the images into the file

In [3]:
file_path = 'D:\Admin\Documents\Year_4\AMLS\Assessment\dataset_AMLS_20-21\cartoon_set\img'
def load_images(file_path):
    sample_size = 7500
    images = []
    hogs = []
    hogimg = []
    mags = []
    angles = []
    counter = 0
    for filename in os.listdir(file_path):
        img = cv2.imread(os.path.join(file_path, filename))
        if img is not None:
            dim = (64,128)
            scaled = cv2.resize(img, dim, interpolation=cv2.INTER_AREA)
            gray = cv2.cvtColor(scaled, cv2.COLOR_BGR2GRAY)
            gray = np.float32(gray)/255.0
            images.append(gray)
            feat, vis = hog(gray, visualize=True)
            hogs.append(feat)
            hogimg.append(vis)
            gx = cv2.Sobel(gray, cv2.CV_32F, 1, 0, ksize=1)
            gy = cv2.Sobel(gray, cv2.CV_32F, 0, 1, ksize=1)
            mag, angle = cv2.cartToPolar(gx, gy, angleInDegrees=True)
            mags.append(mag)
            angles.append(angle)
            counter += 1
        if counter > sample_size - 1:
            break
    return images, mags, angles, hogs, hogimg
images, mags, angles, hogs, hogimg = load_images(file_path)

Next we load the labels

In [4]:
label_data = pd.read_csv(r'D:\Admin\Documents\Year_4\AMLS\Assessment\dataset_AMLS_20-21\cartoon_set\labels.csv')
face_shape_labels = pd.DataFrame(label_data)
face_shape_labels = face_shape_labels[face_shape_labels.columns[2]]
face_shape_labels = face_shape_labels[:7500]
headings = ["Index", "Eye Colour", "Face Shape", "File Name"]
print(face_shape_labels)

0       4
1       4
2       3
3       0
4       2
       ..
7495    2
7496    4
7497    0
7498    2
7499    4
Name: face_shape, Length: 7500, dtype: int64


In [5]:
print(images[0])

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [6]:
print(mags[0])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [7]:
print(angles[0])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
print(hogimg[0])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


So we know that the label data has been extracted properly. The following code checks if the images have been preprocessed properly

In [ ]:
cv2.imshow('Gray Image', hogimg[0])
cv2.waitKey()
cv2.destroyAllWindows()

Here we split the data to test and train.

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(hogs,face_shape_labels, test_size=0.25)
print(x_train[0])
print(y_train)
# estimator = Estimator(meta_algo='RF', verbose=3)
# estimation, lb, ub = estimator.time(SVC(), x_train, y_train)
# print(ub)

In [ ]:
# classifier = svm.SVC(kernel='linear')
classifier = LinearSVC(max_iter=1100)
classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_test)
accuracy = metrics.accuracy_score(y_test,y_pred=y_pred)
print(accuracy)

In [ ]:
cv2.imshow('Gray Image', hogimg[0])
cv2.waitKey()
cv2.destroyAllWindows()

Here we split the data to test and train.

In [9]:
x_train, x_test, y_train, y_test = train_test_split(hogs,face_shape_labels, test_size=0.25)
print(x_train[0])
print(y_train)
# estimator = Estimator(meta_algo='RF', verbose=3)
# estimation, lb, ub = estimator.time(SVC(), x_train, y_train)
# print(ub)

[0. 0. 0. ... 0. 0. 0.]
6849    1
6698    0
6221    3
4094    4
7002    0
       ..
698     1
2578    0
6918    2
1941    0
6326    0
Name: face_shape, Length: 5625, dtype: int64


In [10]:
# classifier = svm.SVC(kernel='linear')
classifier = LinearSVC(max_iter=1100)
classifier.fit(x_train, y_train)

C:\Users\Admin\.conda\envs\AMLS\lib\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(max_iter=1100)

In [11]:
y_pred = classifier.predict(x_test)
accuracy = metrics.accuracy_score(y_test,y_pred=y_pred)
print(accuracy)

0.1904
